// <auto-generated />
using System;
using EcoDenuncia.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EcoDenuncia.Migrations
{
    [DbContext(typeof(EcoDenunciaContext))]
    [Migration("20250602141435_UpdateBairroMapping")]
    partial class UpdateBairroMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.AcompanhamentoDenuncia", b =>
                {
                    b.Property<Guid>("IdAcompanhamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("IdDenuncia")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdAcompanhamento");

                    b.HasIndex("IdDenuncia");

                    b.ToTable("TBL_ACOMPANHAMENTO_DENUNCIAS", (string)null);
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Bairro", b =>
                {
                    b.Property<Guid>("IdBairro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_bairro");

                    b.Property<Guid>("IdCidade")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_cidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.HasKey("IdBairro");

                    b.HasIndex("IdCidade");

                    b.ToTable("TBL_BAIRRO", (string)null);
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Cidade", b =>
                {
                    b.Property<Guid>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_cidade");

                    b.Property<Guid>("IdEstado")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.HasKey("IdCidade");

                    b.HasIndex("IdEstado");

                    b.ToTable("TBL_CIDADE", (string)null);
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Denuncia", b =>
                {
                    b.Property<Guid>("IdDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<Guid>("IdLocalizacao")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("IdOrgaoPublico")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("LocalizacaoIdLocalização")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("OrgaoPublicoIdOrgaoPublico")
                        .HasColumnType("RAW(16)");

                    b.HasKey("IdDenuncia");

                    b.HasIndex("IdLocalizacao");

                    b.HasIndex("IdOrgaoPublico");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("LocalizacaoIdLocalização");

                    b.HasIndex("OrgaoPublicoIdOrgaoPublico");

                    b.ToTable("TBL_DENUNCIAS", (string)null);
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Estado", b =>
                {
                    b.Property<Guid>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("uf");

                    b.HasKey("IdEstado");

                    b.ToTable("TBL_ESTADO", (string)null);
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Localizacao", b =>
                {
                    b.Property<Guid>("IdLocalização")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<Guid>("IdBairro")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.HasKey("IdLocalização");

                    b.HasIndex("IdBairro");

                    b.ToTable("TBL_LOCALIZACAO", (string)null);
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.OrgaoPublico", b =>
                {
                    b.Property<Guid>("IdOrgaoPublico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AreaAtuacao")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.HasKey("IdOrgaoPublico");

                    b.ToTable("TBL_ORGAO_PUBLICO", (string)null);
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdUsuario");

                    b.ToTable("TBL_USUARIOS", (string)null);
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.AcompanhamentoDenuncia", b =>
                {
                    b.HasOne("EcoDenuncia.Infrastructure.Persistence.Denuncia", "Denuncia")
                        .WithMany()
                        .HasForeignKey("IdDenuncia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Bairro", b =>
                {
                    b.HasOne("EcoDenuncia.Infrastructure.Persistence.Cidade", "Cidade")
                        .WithMany("Bairros")
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Cidade", b =>
                {
                    b.HasOne("EcoDenuncia.Infrastructure.Persistence.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Denuncia", b =>
                {
                    b.HasOne("EcoDenuncia.Infrastructure.Persistence.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("IdLocalizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoDenuncia.Infrastructure.Persistence.OrgaoPublico", "OrgaoPublico")
                        .WithMany()
                        .HasForeignKey("IdOrgaoPublico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoDenuncia.Infrastructure.Persistence.Usuario", "Usuario")
                        .WithMany("Denuncias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoDenuncia.Infrastructure.Persistence.Localizacao", null)
                        .WithMany("Denuncias")
                        .HasForeignKey("LocalizacaoIdLocalização");

                    b.HasOne("EcoDenuncia.Infrastructure.Persistence.OrgaoPublico", null)
                        .WithMany("Denuncias")
                        .HasForeignKey("OrgaoPublicoIdOrgaoPublico");

                    b.Navigation("Localizacao");

                    b.Navigation("OrgaoPublico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Localizacao", b =>
                {
                    b.HasOne("EcoDenuncia.Infrastructure.Persistence.Bairro", "Bairro")
                        .WithMany("Localizacoes")
                        .HasForeignKey("IdBairro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Bairro", b =>
                {
                    b.Navigation("Localizacoes");
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Cidade", b =>
                {
                    b.Navigation("Bairros");
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Localizacao", b =>
                {
                    b.Navigation("Denuncias");
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.OrgaoPublico", b =>
                {
                    b.Navigation("Denuncias");
                });

            modelBuilder.Entity("EcoDenuncia.Infrastructure.Persistence.Usuario", b =>
                {
                    b.Navigation("Denuncias");
                });
#pragma warning restore 612, 618
        }
    }
}
